firmware        = "efi"
build_type      = "en-datacenter-core"
build_os        = "wins2025"
guest_os_type   = "windows2022srvnext-64"
iso_path        = "https://go.microsoft.com/fwlink/?linkid=2293312&clcid=0x409&culture=en-us&country=us"
iso_checksum    = "none"
disk_size       =  "65536"
ssh_password    = "VMware1!"
cd_files        = ["build/iso/VMware-tools-windows-13.0.0-24696409.iso",]